# Name of workflow
name: NodeJS

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make setup
      - run: make tests
      - run: make linter
